weatherMap = {
	"Aliquippa": "Aliquippa",
	"Allentown": "Allentown",
	"Altoona": "Altoona",
	"Arnold": "Arnold",
	"Beaver Falls": "Beaver Falls",
	"Bethlehem": "Bethlehem",
	"Bradford": "Bradford",
	"Butler": "Butler",
	"Carbondale": "Carbondale",
	"Chester": "Chester",
	"Clairton": "Clairton",
	"Coatesville": "Coatesville",
	"Connellsville": "Connellsville",
	"Corry": "Corry",
	"DuBois": "DuBois",
	"Duquesne": "Duquesne",
	"Easton": "Easton",
	"Erie": "Erie",
	"Farrell": "Farrell",
	"Franklin": "Franklin",
	"Greensburg": "Greensburg",
	"Harrisburg": "Harrisburg",
	"Hazleton": "Hazleton",
	"Hermitage": "Hermitage",	
	"Jeannette": "Jeannette",
	"Johnstown": "Johnstown",
	"Lancaster": "Lancaster",
	"Latrobe": "Latrobe",
	"Lebanon": "Lebanon",
	"Lock Haven": "Lock Haven",
	"Lower Burrell": "Lower Burrell",
	"McKeesport": "McKeesport",
	"Meadville": "Meadville",
	"Monessen": "Monessen",
	"Monongahela": "Monongahela",
	"Nanticoke": "Nanticoke",
	"New Castle": "New Castle",
	"New Kensington": "New Kensington",
	"Oil City": "Oil City",
	"Parker": "Parker",
	"Philadelphia": "Philadelphia",
	"Pittsburgh": "Pittsburgh",
	"Pittston": "Pittston",
	"Pottsville": "Pottsville",
	"Reading": "Reading",
	"St. Marys": "St. Marys",
	"Scranton": "Scranton",
	"Shamokin": "Shamokin",
	"Sharon": "Sharon",
	"Sunbury": "Sunbury",
	"Titusville": "Titusville",
	"Uniontown": "Uniontown",
	"Warren": "Warren",
	"Washington": "Washington",
	"Wilkes-Barre": "Wilkes-Barre",
	"Williamsport": "Williamsport",
	"York": "York",
	"aliquippa": "Aliquippa",
	"allentown": "Allentown",
	"altoona": "Altoona",
	"arnold": "Arnold",
	"beaver Falls": "Beaver Falls",
	"bethlehem": "Bethlehem",
	"bradford": "Bradford",
	"butler": "Butler",
	"carbondale": "Carbondale",
	"chester": "Chester",
	"clairton": "Clairton",
	"coatesville": "Coatesville",
	"connellsville": "Connellsville",
	"corry": "Corry",
	"dubois": "DuBois",
	"duquesne": "Duquesne",
	"easton": "Easton",
	"erie": "Erie",
	"farrell": "Farrell",
	"franklin": "Franklin",
	"greensburg": "Greensburg",
	"harrisburg": "Harrisburg",
	"hazleton": "Hazleton",
	"hermitage": "Hermitage",	
	"jeannette": "Jeannette",
	"johnstown": "Johnstown",
	"lancaster": "Lancaster",
	"latrobe": "Latrobe",
	"lebanon": "Lebanon",
	"lock Haven": "Lock Haven",
	"lower Burrell": "Lower Burrell",
	"mckeesport": "McKeesport",
	"meadville": "Meadville",
	"monessen": "Monessen",
	"monongahela": "Monongahela",
	"nanticoke": "Nanticoke",
	"new castle": "New Castle",
	"new kensington": "New Kensington",
	"oil city": "Oil City",
	"parker": "Parker",
	"philadelphia": "Philadelphia",
	"pittsburgh": "Pittsburgh",
	"pittston": "Pittston",
	"pottsville": "Pottsville",
	"reading": "Reading",
	"st. marys": "St. Marys",
	"scranton": "Scranton",
	"shamokin": "Shamokin",
	"sharon": "Sharon",
	"sunbury": "Sunbury",
	"titusville": "Titusville",
	"uniontown": "Uniontown",
	"warren": "Warren",
	"washington": "Washington",
	"wilkes-Barre": "Wilkes-Barre",
	"williamsport": "Williamsport",
	"york": "York"
}
