searchMap = {
	a: ["Aliquippa | ", "Allentown | ", "Altoona | ", "Arnold"],
	b: ["Beaver Falls | ", "Bethlehem | ", "Bradford | ", "Butler"],
	c: ["Carbondale | ", "Chester | ", "Clairton | ", "Coatesville | ", "Connellsville | ", "Corry"],
	d: ["DuBois | ", "Duquesne"],
	e: ["Easton | ", "Erie"],
	f: ["Farrell | ", "Franklin"],
	g: ["Greensburg"],
	h: ["Harrisburg | ", "Hazleton | ", "Hermitage"],	
	i: ["Did you know that there are no cities in Pennsylvania, that start with an I"],
	j: ["Jeannette | ", "Johnstown"],
	k: ["Did you know that there are no cities in Pennsylvania, that start with a K"],
	l: ["Lancaster | ", "Latrobe | ", "Lebanon | ", "Lock Haven | ", "Lower Burrell"],
	m: ["McKeesport | ", "Meadville | ", "Monessen | ", "Monongahela"],
	n: ["Nanticoke | ", "New Castle | ", "New Kensington"],
	o: ["Oil City"],
	p: ["Parker | ", "Philadelphia | ", "Pittsburgh | ", "Pittston | ", "Pottsville"],
	q: ["Quincy IL"],
	r: ["Reading"],
	s: ["St. Marys | ", "Scranton | ", "Shamokin | ", "Sharon | ", "Sunbury"],
	t: ["Titusville"],
	u: ["Uniontown"],
	v: ["Virginia Beach VA"],
	w: ["Warren | ", "Washington | ", "Wilkes-Barre | ", "Williamsport"],
	x: ["Did you know that there are no cities in Pennsylvania, that start with an X"],
	y: ["York"],
	z: ["Did you know that there are no cities in Pennsylvania, that start with a Z"]
	
}